name: Merge Upstream Changes

on:
  schedule:
    - cron: '0 * * * *' # Runs at the start of every hour

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout fork's main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Configure git
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'

    - name: Add upstream remote and fetch latest changes
      run: |
        git remote add upstream https://github.com/KelvinTegelaar/CIPP-API.git
        git fetch upstream main

    - name: Merge upstream changes
      run: |
        git merge upstream/main --no-edit
        git push origin main
